In [2]:
import numpy as np
import pandas as pd
import sklearn
from sklearn import metrics
from sklearn import datasets
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.preprocessing import normalize
import scipy.cluster.hierarchy as shc
from sklearn import model_selection
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [3]:
employee = pd.read_csv("employee")
display(employee)

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No   
1     Bachelors         2013       Pune            1   28  Female          No   
2     Bachelors         2014  New Delhi            3   38  Female          No   
3       Masters         2016  Bangalore            3   27    Male          No   
4       Masters         2017       Pune            3   24    Male         Yes   
...         ...          ...        ...          ...  ...     ...         ...   
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 9 columns]

In [4]:
employee1 = employee.drop(["JoiningYear","Age","EverBenched", "ExperienceInCurrentDomain", "LeaveOrNot"], axis = 1)

In [5]:
#changing the categorical values to numerical values in order to do a cluster
employee1_mapped = employee1.copy()
employee1_mapped["Education"] = employee1_mapped["Education"].map({"Bachelors":11,"Masters":12,"PHD":13})
employee1_mapped["City"] = employee1_mapped["City"].map({"Bangalore":6,"Pune": 7,"New Delhi":8})
employee1_mapped["Gender"] = employee1_mapped["Gender"].map({"Male":9,"Female": 10})
employee1_mapped

Education  City  PaymentTier  Gender
0            11     6            3       9
1            11     7            1      10
2            11     8            3      10
3            12     6            3       9
4            12     7            3       9
...         ...   ...          ...     ...
4648         11     6            3      10
4649         12     7            2       9
4650         12     8            3       9
4651         11     6            3       9
4652         11     6            3       9

[4653 rows x 4 columns]

In [6]:
#scaled the data 

employee1_mapped_scaled = normalize(employee1_mapped)
employee1_mapped_scaled = pd.DataFrame(employee1_mapped_scaled, columns=employee1_mapped.columns)
employee1_mapped_scaled.head()

Education      City  PaymentTier    Gender
0   0.699913  0.381771     0.190885  0.572656
1   0.668202  0.425220     0.060746  0.607457
2   0.641533  0.466569     0.174964  0.583212
3   0.730297  0.365148     0.182574  0.547723
4   0.713326  0.416107     0.178331  0.534994

In [7]:
X= employee1_mapped.iloc[:, 1:5].values
Y= employee1_mapped.iloc[:,2].values

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn import datasets
from sklearn import metrics
lm = LogisticRegression()
X_train, X_test, Y_train, Y_test = sklearn.model_selection.train_test_split(X, Y, test_size=0.30)
lm.fit(X_train, Y_train)
lm.predict_proba(X_test)
predicted = lm.predict(X_test)
print(metrics.classification_report(Y_test, predicted))
print(metrics.confusion_matrix(Y_test, predicted))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        72
           2       1.00      1.00      1.00       283
           3       1.00      1.00      1.00      1041

    accuracy                           1.00      1396
   macro avg       1.00      1.00      1.00      1396
weighted avg       1.00      1.00      1.00      1396

[[  72    0    0]
 [   0  283    0]
 [   0    0 1041]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:
from sklearn.tree import DecisionTreeClassifier
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, Y, test_size=0.30)
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print(model)
predicted = model.predict(X_test)
print(metrics.classification_report(y_test, predicted))
print(metrics.confusion_matrix(y_test, predicted))


DecisionTreeClassifier()
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        79
           2       1.00      1.00      1.00       268
           3       1.00      1.00      1.00      1049

    accuracy                           1.00      1396
   macro avg       1.00      1.00      1.00      1396
weighted avg       1.00      1.00      1.00      1396

[[  79    0    0]
 [   0  268    0]
 [   0    0 1049]]


In [10]:
from sklearn.neighbors import KNeighborsClassifier
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, Y, test_size=0.30)
model = KNeighborsClassifier()
model.fit(X_train, y_train)
print(model)
predicted = model.predict(X_test)
print(metrics.classification_report(y_test, predicted))
print(metrics.confusion_matrix(y_test, predicted))


KNeighborsClassifier()
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        91
           2       1.00      1.00      1.00       285
           3       1.00      1.00      1.00      1020

    accuracy                           1.00      1396
   macro avg       1.00      1.00      1.00      1396
weighted avg       1.00      1.00      1.00      1396

[[  91    0    0]
 [   0  285    0]
 [   0    0 1020]]


In [11]:
from sklearn.naive_bayes import GaussianNB
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, Y, test_size=0.30)
model = GaussianNB()
model.fit(X_train, y_train)
print(model)
predicted = model.predict(X_test)
print(metrics.classification_report(Y_test, predicted))
print(metrics.confusion_matrix(Y_test, predicted))


GaussianNB()
              precision    recall  f1-score   support

           1       0.05      0.06      0.05        72
           2       0.16      0.16      0.16       283
           3       0.73      0.73      0.73      1041

    accuracy                           0.58      1396
   macro avg       0.31      0.31      0.31      1396
weighted avg       0.58      0.58      0.58      1396

[[  4  13  55]
 [ 18  44 221]
 [ 62 221 758]]
